spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fitness_db?useUnicode=true&characterEncoding=utf8mb4&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 10s
      lettuce:
        pool:
          min-idle: 1
          max-idle: 8
          max-active: 8

logging:
  level:
    com.fitness: debug
    com.fitness.module: debug
